github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/youjizz-downloader",
  "https://serp.co/products/youjizz-downloader/reviews/",
  "https://extensions.serp.co/youjizz-downloader",
  "https://browserextensions.io/youjizz-downloader"
]
